# Generated by Django 5.2.6 on 2025-09-27 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slug', models.CharField(max_length=25, unique=True)),
                ('logo', models.ImageField(upload_to='brands-logo/')),
            ],
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('slug', models.CharField(max_length=125, unique=True)),
                ('main_image', models.ImageField(upload_to='ModelAuto/main/')),
                ('year', models.IntegerField(choices=[(2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], db_index=True, default=2025, verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, help_text='Объем в литрах (от 0.1 до 12.5 л)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12.5)], verbose_name='Объем двигателя')),
                ('horse_power', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лошадиные силы')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.brand', verbose_name='Марка авто')),
                ('drive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.drivetype', verbose_name='Привод')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.fueltype', verbose_name='Тип Топлива')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.transmission', verbose_name='Трансмиссия')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelAutoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ModelAuto/extra')),
                ('modelauto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.modelauto')),
            ],
        ),
    ]
